#  Druid on K8S
#  Copyright (c) 2023-present NAVER Corp.
#  Apache-2.0
{{- if .Values.kerberos.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keytab
type: Opaque
data:
  keytab: {{ .Values.kerberos.keytab }}
{{- end }}