apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-turnilo
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-turnilo
  ports:
    - name: {{ .Release.Name }}-turnilo
      port: 9090
      protocol: TCP
      targetPort: 9090
